stages:
  - test
  - deploy

test:python2.7:
  image: "python:2.7"
  services:
    - mongo:latest
    - redis:latest
  stage: test
  script:
    - pip install tox
    - tox -e py27

test:python3.4:
  image: "python:3.4"
  services:
    - mongo:latest
    - redis:latest
  stage: test
  script:
    - pip install tox
    - tox -e py34

test:python3.5:
  image: "python:3.5"
  services:
    - mongo:latest
    - redis:latest
  stage: test
  script:
    - pip install tox
    - tox -e py35
    
test:python3.6:
  image: "python:3.6"
  services:
    - mongo:latest
    - redis:latest
  stage: test
  script:
    - pip install tox
    - tox -e py36
    
test:python3.7:
  image: "python:3.7"
  services:
    - mongo:latest
    - redis:latest
  stage: test
  script:
    - pip install tox
    - tox -e py37
    
deploy_job:
  stage: deploy
  script:
    - pip list
  when: manual
