coverage:
  notify:
    slack:
      default:
        url: "secret:z2ih137BbhBMQmSAa8NXhR3pswp+30TlWp2MEihwq5LBhV1V1a+SH9BH4J1mzHQ6T6zWHNeYvkH5K+ndXTlVFCAf1NqI0gcZkZfCg1xqMTIh/lOEWqzxdpm8MGJ7VDxb+tLjccOzzBwL8oYhO7SI6kTi745b7c7pbqTsp3V1lVw="
