from unittest import TestCase

from doe2_sim_parser.parse_report_bepu import parse_bepu
from tests import SAMPLE_SIM_BEPU


class ParseReportBEPUTest(TestCase):
    maxDiff = None

    def setUp(self):
        with SAMPLE_SIM_BEPU.open() as f:
            self.report = f.readlines()

        self.report_csv = [
            ["sample", "DOE-2.2-48z", "2/24/2019", "4:28:19", "1"],
            [
                "REPORT",
                "BEPU",
                "Building Utility Performance",
                "WEATHER FILE",
                "CHICAGO, IL",
            ],
            [
                "METER",
                "TYPE",
                "UNIT",
                "LIGHTS",
                "TASK\nLIGHTS",
                "MISC\nEQUIP",
                "SPACE\nHEATING",
                "SPACE\nCOOLING",
                "HEAT\nREJECT",
                "PUMPS\n& AUX",
                "VENT\nFANS",
                "REFRIG\nDISPLAY",
                "HT PUMP\nSUPPLEN",
                "DOMEST\nHOT WTR",
                "EXT\nUSAGE",
                "TOTAL",
            ],
            [
                "EM1",
                "ELECTRICITY",
                "KWH",
                "2482833.",
                "0.",
                "1388473.",
                "0.",
                "392865.",
                "59242.",
                "409115.",
                "287555.",
                "0.",
                "0.",
                "0.",
                "0.",
                "5020082.",
            ],
            [
                "FM1",
                "NATURAL-GAS",
                "THERM",
                "0.",
                "0.",
                "0.",
                "36623.",
                "0.",
                "0.",
                "0.",
                "0.",
                "0.",
                "0.",
                "10181.",
                "0.",
                "46804.",
            ],
            [
                "Stea",
                "STEAM",
                "MBTU",
                "0.",
                "0.",
                "0.",
                "1426.",
                "0.",
                "0.",
                "0.",
                "0.",
                "0.",
                "0.",
                "0.",
                "0.",
                "1426.",
            ],
            [
                "Stea",
                "STEAM",
                "MBTU",
                "0.",
                "0.",
                "0.",
                "0.",
                "0.",
                "0.",
                "0.",
                "0.",
                "0.",
                "0.",
                "699.",
                "0.",
                "699.",
            ],
            [
                "Chil",
                "CHILLED-WATER",
                "MBTU",
                "0.",
                "0.",
                "0.",
                "0.",
                "3311.",
                "0.",
                "0.",
                "0.",
                "0.",
                "0.",
                "0.",
                "0.",
                "3311.",
            ],
            [
                "TOTAL ELECTRICITY",
                "ELECTRICITY",
                "5020082.",
                "KWH",
                "6.692",
                "KWH",
                "/SQFT-YR GROSS-AREA",
                "6.692",
                "KWH",
                "/SQFT-YR NET-AREA",
            ],
            [
                "TOTAL NATURAL-GAS",
                "NATURAL-GAS",
                "46804.",
                "THERM",
                "0.062",
                "THERM",
                "/SQFT-YR GROSS-AREA",
                "0.062",
                "THERM",
                "/SQFT-YR NET-AREA",
            ],
            [
                "TOTAL STEAM",
                "STEAM",
                "2125.",
                "MBTU",
                "0.003",
                "MBTU",
                "/SQFT-YR GROSS-AREA",
                "0.003",
                "MBTU",
                "/SQFT-YR NET-AREA",
            ],
            [
                "TOTAL CHILLED-WATE",
                "CHILLED-WATE",
                "3311.",
                "MBTU",
                "0.004",
                "MBTU",
                "/SQFT-YR GROSS-AREA",
                "0.004",
                "MBTU",
                "/SQFT-YR NET-AREA",
            ],
            ["PERCENT OF HOURS ANY SYSTEM ZONE OUTSIDE OF THROTTLING RANGE", "9.30"],
            ["PERCENT OF HOURS ANY PLANT LOAD NOT SATISFIED", "0.00"],
            ["HOURS ANY ZONE ABOVE COOLING THROTTLING RANGE", "7"],
            ["HOURS ANY ZONE BELOW HEATING THROTTLING RANGE", "250"],
            ["NOTE:  ENERGY IS APPORTIONED HOURLY TO ALL END-USE CATEGORIES."],
        ]

    def tearDown(self):
        pass

    def test_parse_bepu(self):
        self.assertSequenceEqual(parse_bepu(self.report), self.report_csv)
