from unittest import TestCase

from doe2_sim_parser.parse_report_beps import parse_beps
from doe2_sim_parser.utils.data_types import Report
from tests import SAMPLE_SIM_BEPS


class ParseReportBEPSTest(TestCase):
    maxDiff = None

    def setUp(self):
        with SAMPLE_SIM_BEPS.open() as f:
            self.report = Report(
                type_='normal_reports',
                code='BEPS',
                name='Building Energy Performance',
                report=f.readlines(),
                report_no=None,
                page_no=None
            )

        self.report_csv = [
            ["sample", "DOE-2.2-48z", "2/24/2019", "4:28:19", "1"],
            [
                "REPORT",
                "BEPS",
                "Building Energy Performance",
                "WEATHER FILE",
                "CHICAGO, IL",
            ],
            [
                "METER",
                "TYPE",
                "UNIT",
                "LIGHTS",
                "TASK\nLIGHTS",
                "MISC\nEQUIP",
                "SPACE\nHEATING",
                "SPACE\nCOOLING",
                "HEAT\nREJECT",
                "PUMPS\n& AUX",
                "VENT\nFANS",
                "REFRIG\nDISPLAY",
                "HT PUMP\nSUPPLEN",
                "DOMEST\nHOT WTR",
                "EXT\nUSAGE",
                "TOTAL",
            ],
            [
                "EM1",
                "ELECTRICITY",
                "MBTU",
                "8474.0",
                "0.0",
                "4739.0",
                "0.0",
                "1341.0",
                "202.2",
                "1396.0",
                "981.4",
                "0.0",
                "0.0",
                "0.0",
                "0.0",
                "17133.0",
            ],
            [
                "FM1",
                "NATURAL-GAS",
                "MBTU",
                "0.0",
                "0.0",
                "0.0",
                "3662.0",
                "0.0",
                "0.0",
                "0.0",
                "0.0",
                "0.0",
                "0.0",
                "1018.0",
                "0.0",
                "4680.4",
            ],
            [
                "Stea",
                "STEAM",
                "MBTU",
                "0.0",
                "0.0",
                "0.0",
                "1426.0",
                "0.0",
                "0.0",
                "0.0",
                "0.0",
                "0.0",
                "0.0",
                "0.0",
                "0.0",
                "1426.1",
            ],
            [
                "Stea",
                "STEAM",
                "MBTU",
                "0.0",
                "0.0",
                "0.0",
                "0.0",
                "0.0",
                "0.0",
                "0.0",
                "0.0",
                "0.0",
                "0.0",
                "698.7",
                "0.0",
                "698.7",
            ],
            [
                "Chil",
                "CHILLED-WATER",
                "MBTU",
                "0.0",
                "0.0",
                "0.0",
                "0.0",
                "3311.0",
                "0.0",
                "0.0",
                "0.0",
                "0.0",
                "0.0",
                "0.0",
                "0.0",
                "3311.2",
            ],
            [
                "",
                "",
                "MBTU",
                "8474.0",
                "0.0",
                "4739.0",
                "5088.0",
                "4652.0",
                "202.2",
                "1396.0",
                "981.4",
                "0.0",
                "0.0",
                "1717.0",
                "0.0",
                "27250.0",
            ],
            [
                "TOTAL SITE ENERGY",
                "27249.80",
                "MBTU",
                "36.3",
                "KBTU/SQFT-YR GROSS-AREA",
                "36.3",
                "KBTU/SQFT-YR NET-AREA",
            ],
            [
                "TOTAL SOURCE ENERGY",
                "61829.30",
                "MBTU",
                "82.4",
                "KBTU/SQFT-YR GROSS-AREA",
                "82.4",
                "KBTU/SQFT-YR NET-AREA",
            ],
            ["PERCENT OF HOURS ANY SYSTEM ZONE OUTSIDE OF THROTTLING RANGE",
             "9.30"],
            ["PERCENT OF HOURS ANY PLANT LOAD NOT SATISFIED", "0.00"],
            ["HOURS ANY ZONE ABOVE COOLING THROTTLING RANGE", "7"],
            ["HOURS ANY ZONE BELOW HEATING THROTTLING RANGE", "250"],
            ["NOTE:  ENERGY IS APPORTIONED HOURLY TO ALL END-USE CATEGORIES."],
        ]

    def tearDown(self):
        pass

    def test_parse_beps(self):
        self.assertSequenceEqual(parse_beps([self.report]), self.report_csv)
