TARGET_REPORTS = {
    'BEPS': 'Building Energy Performance',
    'BEPU': 'Building Utility Performance',
    'LS-A': 'Space Peak Loads Summary',
    'LS-B': 'Space Peak Loads Components',
    'LS-C': 'Building Peak Load Components',
    'LS-D': 'Building Monthly Loads Summary',
    'LS-E': 'Space Monthly Load Components',
    'LS-F': 'Building Monthly Load Component',
    'LS-K': 'Building Input Fuels Summary',
    'LS-L': 'Management and Solar Summary',
    'LV-A': 'General Project Parameters',
    'LV-B': 'Summary of Spaces',
    'LV-C': 'Details of Space',
    'LV-D': 'Details of Exterior Surface',
    'LV-E': 'Details of Underground Surfaces',
    'LV-F': 'Details of Interior Surfaces',
    'LV-G': 'Details of Schedules',
    'LV-H': 'Details of Windows',
    'LV-I': 'Details of Constructions',
    'LV-J': 'Details of Building Shades',
    'LV-M': 'DOE-2.2 Units Conversion Table',
    'LV-N': 'Building Coordinate Geometry',
    'PS-A': 'Plant Energy Utilization',
    'PS-B': 'Utility and Fuel Use Summary',
    'PS-C': 'Equipment Loads and Energy Use',
    'PS-D': 'Circulation Loop Loads',
    'PS-E': 'Energy End-Use Summary',
    'PS-F': 'Energy End-Use Summary',
    'PS-H': 'Loads and Energy Usage',
    'PV-A': 'Plant Design Parameters',
    'SS-D': 'Building HVAC Load Summary',
    'SS-E': 'Building HVAC Load Hours',
    'SS-M': 'Building HVAC Fan Elec Energy',
    'SV-A': 'System Design Parameters',
    'SS-A': 'System Loads Summary',
    'SS-B': 'System Loads Summary',
    'SS-C': 'System Load Hours',
    'SS-F': 'Zone Demand Summary',
    'SS-G': 'Zone Loads Summary',
    'SS-H': 'System Utility Energy Use',
    'SS-I': 'Sensible/Latent Summary',
    'SS-J': 'Peak Heating and Cooling',
    'SS-K': 'Space Temperature Summary',
    'SS-O': 'Space Temperature Summary',
    'SS-P': 'Heating Performance Summery',
    'SS-R': 'Zone Performance Summary',
    'SS-L': 'Fan Electric Energy Use',
    'SS-N': 'Relative Humidity Summary'
}
