from .utils.data_types import Report

TARGET_REPORTS = (
    Report(type_='normal_report', code='BEPS',
           name='Building Energy Performance', report=None),
    Report(type_='normal_report', code='BEPU',
           name='Building Utility Performance', report=None),
    Report(type_='normal_report', code='LS-A', name='Space Peak Loads Summary',
           report=None),
    Report(type_='normal_report', code='LS-B',
           name='Space Peak Loads Components', report=None),
    Report(type_='normal_report', code='LS-C',
           name='Building Peak Load Components', report=None),
    Report(type_='normal_report', code='LS-D',
           name='Building Monthly Loads Summary', report=None),
    Report(type_='normal_report', code='LS-E',
           name='Space Monthly Load Components', report=None),
    Report(type_='normal_report', code='LS-F',
           name='Building Monthly Load Component', report=None),
    Report(type_='normal_report', code='LS-K',
           name='Building Input Fuels Summary', report=None),
    Report(type_='normal_report', code='LS-L',
           name='Management and Solar Summary', report=None),
    Report(type_='normal_report', code='LV-A',
           name='General Project Parameters', report=None),
    Report(type_='normal_report', code='LV-B', name='Summary of Spaces',
           report=None),
    Report(type_='normal_report', code='LV-C', name='Details of Space',
           report=None),
    Report(type_='normal_report', code='LV-D',
           name='Details of Exterior Surface', report=None),
    Report(type_='normal_report', code='LV-E',
           name='Details of Underground Surfaces', report=None),
    Report(type_='normal_report', code='LV-F',
           name='Details of Interior Surfaces', report=None),
    Report(type_='normal_report', code='LV-G', name='Details of Schedules',
           report=None),
    Report(type_='normal_report', code='LV-H', name='Details of Windows',
           report=None),
    Report(type_='normal_report', code='LV-I', name='Details of Constructions',
           report=None),
    Report(type_='normal_report', code='LV-J',
           name='Details of Building Shades', report=None),
    Report(type_='normal_report', code='LV-M',
           name='DOE-2.2 Units Conversion Table', report=None),
    Report(type_='normal_report', code='LV-N',
           name='Building Coordinate Geometry', report=None),
    Report(type_='normal_report', code='PS-A', name='Plant Energy Utilization',
           report=None),
    Report(type_='normal_report', code='PS-B',
           name='Utility and Fuel Use Summary', report=None),
    Report(type_='normal_report', code='PS-C',
           name='Equipment Loads and Energy Use', report=None),
    Report(type_='normal_report', code='PS-D', name='Circulation Loop Loads',
           report=None),
    Report(type_='normal_report', code='PS-E', name='Energy End-Use Summary',
           report=None),
    Report(type_='normal_report', code='PS-F', name='Energy End-Use Summary',
           report=None),
    Report(type_='normal_report', code='PS-H', name='Loads and Energy Usage',
           report=None),
    Report(type_='normal_report', code='PV-A', name='Plant Design Parameters',
           report=None),
    Report(type_='normal_report', code='SS-D',
           name='Building HVAC Load Summary', report=None),
    Report(type_='normal_report', code='SS-E', name='Building HVAC Load Hours',
           report=None),
    Report(type_='normal_report', code='SS-M',
           name='Building HVAC Fan Elec Energy', report=None),
    Report(type_='normal_report', code='SV-A', name='System Design Parameters',
           report=None),
    Report(type_='normal_report', code='SS-A', name='System Loads Summary',
           report=None),
    Report(type_='normal_report', code='SS-B', name='System Loads Summary',
           report=None),
    Report(type_='normal_report', code='SS-C', name='System Load Hours',
           report=None),
    Report(type_='normal_report', code='SS-F', name='Zone Demand Summary',
           report=None),
    Report(type_='normal_report', code='SS-G', name='Zone Loads Summary',
           report=None),
    Report(type_='normal_report', code='SS-H', name='System Utility Energy Use',
           report=None),
    Report(type_='normal_report', code='SS-I', name='Sensible/Latent Summary',
           report=None),
    Report(type_='normal_report', code='SS-J', name='Peak Heating and Cooling',
           report=None),
    Report(type_='normal_report', code='SS-K', name='Space Temperature Summary',
           report=None),
    Report(type_='normal_report', code='SS-O', name='Space Temperature Summary',
           report=None),
    Report(type_='normal_report', code='SS-P',
           name='Heating Performance Summery', report=None),
    Report(type_='normal_report', code='SS-R', name='Zone Performance Summary',
           report=None),
    Report(type_='normal_report', code='SS-L', name='Fan Electric Energy Use',
           report=None),
    Report(type_='normal_report', code='SS-N', name='Relative Humidity Summary',
           report=None)
)
