from collections import namedtuple

Report = namedtuple('Report', ['code', 'name'])

TARGET_REPORTS = (
    Report('BEPS', 'Building Energy Performance'),
    Report('BEPU', 'Building Utility Performance'),
    Report('LS-A', 'Space Peak Loads Summary'),
    Report('LS-B', 'Space Peak Loads Components'),
    Report('LS-C', 'Building Peak Load Components'),
    Report('LS-D', 'Building Monthly Loads Summary'),
    Report('LS-E', 'Space Monthly Load Components'),
    Report('LS-F', 'Building Monthly Load Component'),
    Report('LS-K', 'Building Input Fuels Summary'),
    Report('LS-L', 'Management and Solar Summary'),
    Report('LV-A', 'General Project Parameters'),
    Report('LV-B', 'Summary of Spaces'),
    Report('LV-C', 'Details of Space'),
    Report('LV-D', 'Details of Exterior Surface'),
    Report('LV-E', 'Details of Underground Surfaces'),
    Report('LV-F', 'Details of Interior Surfaces'),
    Report('LV-G', 'Details of Schedules'),
    Report('LV-H', 'Details of Windows'),
    Report('LV-I', 'Details of Constructions'),
    Report('LV-J', 'Details of Building Shades'),
    Report('LV-M', 'DOE-2.2 Units Conversion Table'),
    Report('LV-N', 'Building Coordinate Geometry'),
    Report('PS-A', 'Plant Energy Utilization'),
    Report('PS-B', 'Utility and Fuel Use Summary'),
    Report('PS-C', 'Equipment Loads and Energy Use'),
    Report('PS-D', 'Circulation Loop Loads'),
    Report('PS-E', 'Energy End-Use Summary'),
    Report('PS-F', 'Energy End-Use Summary'),
    Report('PS-H', 'Loads and Energy Usage'),
    Report('PV-A', 'Plant Design Parameters'),
    Report('SS-D', 'Building HVAC Load Summary'),
    Report('SS-E', 'Building HVAC Load Hours'),
    Report('SS-M', 'Building HVAC Fan Elec Energy'),
    Report('SV-A', 'System Design Parameters'),
    Report('SS-A', 'System Loads Summary'),
    Report('SS-B', 'System Loads Summary'),
    Report('SS-C', 'System Load Hours'),
    Report('SS-F', 'Zone Demand Summary'),
    Report('SS-G', 'Zone Loads Summary'),
    Report('SS-H', 'System Utility Energy Use'),
    Report('SS-I', 'Sensible/Latent Summary'),
    Report('SS-J', 'Peak Heating and Cooling'),
    Report('SS-K', 'Space Temperature Summary'),
    Report('SS-O', 'Space Temperature Summary'),
    Report('SS-P', 'Heating Performance Summery'),
    Report('SS-R', 'Zone Performance Summary'),
    Report('SS-L', 'Fan Electric Energy Use'),
    Report('SS-N', 'Relative Humidity Summary')
)
